[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.123.7"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production.environment]
  HUGO_ENV = "production"
